### Obtener un usuario por su id
GET http://localhost/Backend_Pt5/api/getuser/1

### Error al no indicar un id
GET http://localhost/Backend_Pt5/api/getuser

### Obtener todos los usuarios
GET http://localhost/Backend_Pt5/api/getusers

### Obtener un articulo por su id
GET http://localhost/Backend_Pt5/api/getarticle/1

### Error al no indicar un id
GET http://localhost/Backend_Pt5/api/getarticle

###  Obtener todos los articulos
GET http://localhost/Backend_Pt5/api/getarticles

###
POST http://localhost/Backend_Pt5/api/refreshtoken
Authorization : Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3Mzg3NTg3ODYsImV4cCI6MTczOTM2MzU4NiwiZGF0YSI6eyJ1c2VybmFtZSI6ImFkbWluIn19.pc1enFhYhA5Ts9mLUhoy5MB07XMYJ_pNCeC8rGYfBqM