name: Deploy to DonDominio

on:
  push:
    branches:
      - master  # Cambia a 'main' si esa es tu rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Upload files to DonDominio via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.ctorres.cat
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./  
        server-dir: /public/
        exclude: |
          *.sql
          assets/**
          README.md
          .git/**
          .github/**
          .gitignore
